export const receitas = [

    {
        id: 1, capa: "/imagens/capa.png",
        titulo: "Roscov",
        tempoPreparo: "25",
        porcoes: "2",
        imagem: "/imagens/foto-1.png",
        iconePorcoes: "/imagens/porcoes.svg",
        iconeTime: "/imagens/time.svg",
        
    },


    {
        id: 2,
        capa: "/imagens/capa.png",
        titulo: "Arroz com pepino",
        tempoPreparo: "35",
        porcoes: "3",
        imagem: "/imagens/foto-2.png",
        iconePorcoes: "/imagens/porcoes.svg",
        iconeTime: "/imagens/time.svg",
    },
    {
        id: 3,
        capa: "/imagens/capa.png",
        titulo: "Ovo com abacate",
        tempoPreparo: "15",
        porcoes: "1",
        imagem: "/imagens/foto-3.png",
        iconePorcoes: "/imagens/porcoes.svg",
        iconeTime: "/imagens/time.svg",
    },
    {
        id: 4,
        capa: "/imagens/capa.png",
        titulo: "Ovo de codorna",
        tempoPreparo: "25",
        porcoes: "2",
        imagem: "/imagens/foto-4.png",
        iconePorcoes: "/imagens/porcoes.svg",
        iconeTime: "/imagens/time.svg",
    },
    {
        id: 5,
        capa: "/imagens/capa.png",
        titulo: "Omelete com abacate",
        tempoPreparo: "35",
        porcoes: "3",
        imagem: "/imagens/foto-5.png",
        iconePorcoes: "/imagens/porcoes.svg",
        iconeTime: "/imagens/time.svg",
    },
    {
        id: 6,
        capa: "/imagens/capa.png",
        titulo: "Ovo com manteiga",
        tempoPreparo: "15",
        porcoes: "1",
        imagem: "/imagens/foto-6.png",
        iconePorcoes: "/imagens/porcoes.svg",
        iconeTime: "/imagens/time.svg",
    },
    {
        id: 7,
        capa: "/imagens/capa.png",
        titulo: "Ovo de codorna",
        tempoPreparo: "25",
        porcoes: "2",
        imagem: "/imagens/foto-7.png",
        iconePorcoes: "/imagens/porcoes.svg",
        iconeTime: "/imagens/time.svg",
    },
    {
        id: 8,
        capa: "/imagens/capa.png",
        titulo: "Omelete com abacate",
        tempoPreparo: "35",
        porcoes: "3",
        imagem: "/imagens/foto-8.png",
        iconePorcoes: "/imagens/porcoes.svg",
        iconeTime: "/imagens/time.svg",
    },
    {
        id: 9,
        capa: "/imagens/capa.png",
        titulo: "Ovo com manteiga",
        tempoPreparo: "15",
        porcoes: "1",
        imagem: "/imagens/foto-9.png",
        iconePorcoes: "/imagens/porcoes.svg",
        iconeTime: "/imagens/time.svg",
    }
]